# Generated by Django 4.1.6 on 2024-03-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botanic', '0004_remove_plant_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
