# Generated by Django 4.1.6 on 2024-03-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botanic', '0005_plant_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
