# Generated by Django 4.1.6 on 2024-03-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botanic', '0006_plant_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPortfoilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfoilio_of_plants', models.ManyToManyField(to='botanic.plant')),
            ],
        ),
    ]
