# Generated by Django 4.1.6 on 2024-03-10 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botanic', '0008_alter_userportfoilio_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPortfoilio',
        ),
    ]
