# Generated by Django 4.1.6 on 2024-03-11 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('botanic', '0010_plant_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='owner',
        ),
        migrations.AddField(
            model_name='plant',
            name='owner',
            field=models.ManyToManyField(blank=True, null=True, related_name='plants', to=settings.AUTH_USER_MODEL),
        ),
    ]
